# .fdroid.yml – metadata for the Zyphastio Flutter app
Categories:
  - Sports & Health
License: MIT
SourceCode: https://github.com/BloodBlinker/Zyphastio
IssueTracker: https://github.com/BloodBlinker/Zyphastio/issues

AutoName: Zyphastio
Summary: Efficient fasting tracker
Description: |
    Zyphastio helps you track your fasting windows effectively.

RepoType: git
Repo: https://github.com/BloodBlinker/Zyphastio.git
