Categories:
  - Sports & Health
License: MIT
SourceCode: https://github.com/BloodBlinker/Zyphastio
IssueTracker: https://github.com/BloodBlinker/Zyphastio/issues

AutoName: Zyphastio
Summary: Efficient fasting tracker
Description: |
    Zyphastio helps you track your fasting windows effectively.

RepoType: git
Repo: https://github.com/BloodBlinker/Zyphastio.git

Builds:
  - versionName: 1.0.11
    versionCode: 12
    commit: v1.0.11
    timeout: 7200
    sudo:
      - apt-get update
      - apt-get -y install curl xz-utils
    output: build/app/outputs/flutter-apk/app-release.apk
    prebuild:
      - chmod +x ./build_fdroid.sh
      - ./build_fdroid.sh prebuild
    build: ./build_fdroid.sh build

AutoUpdateMode: None
UpdateCheckMode: None
CurrentVersion: 1.0.11
CurrentVersionCode: 12
