# .fdroid.yml – metadata for the Zyphastio Flutter app
Categories:
  - Productivity
  - Utilities
License: MIT
SourceCode: https://github.com/your-org/zyphastio
IssueTracker: https://github.com/your-org/zyphastio/issues
Changelog: https://github.com/your-org/zyphastio/blob/main/CHANGELOG.md
Donate: https://github.com/sponsors/your-org

# Build configuration – F-Droid builds the APK itself
Builds:
  - versionName: 1.0.9
    versionCode: 10
    commit: v1.0.9
    subdir: .
    gradle:
      - "app"
    # The command F-Droid runs (Flutter 3.22+ required, or matches SDK constraint)
    # This mirrors the local command we verified:
    #   flutter build apk --release
    # F-Droid will auto-sign the APK.
